language: php
sudo: required

php:
  - 7.3
  - 7.4snapshot
  - nightly

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - composer self-update
  - composer install
  - mysql -uroot -e "create database tmp"

script:
  - phpunit


notifications:
  email: false
